config/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index_login, name = 'index_login' ),
    path('index', views.index, name= 'index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),

    #qna
    path('notice/', include('notice.urls')),
    #공지
    path('main/', include('main.urls')),

    #네이버 크롤링
    path('naver_crawling/', include('naver_crawling.urls')),

    #covid
    path('covid/', include('covid.urls')),
    # path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('users/password_reset_complete/', views.view_complete, name="password_reset_complete"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete2'),
    path('account/', include('allauth.urls')),  #소셜로그인 추가부분
    path('account/google/login/callback/index/',views.index),
    path('account/kakao/login/callback/index/',views.index),
    path('account/naver/login/callback/index/',views.index),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from main.views import index, blog, posting
from.views import *

from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('blog/', blog, name='blog'),
    path('blog/<int:pk>/', posting, name='posting'),
    path('fileupload/', fileUpload, name="fileupload"),
    path('blog/new_post/', new_post, name="new_post"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

class Post(models.Model):
    postname = models.CharField(max_length=50)
    # 게시글 Post에 이미지 추가
    mainphoto = models.ImageField(upload_to="", blank=True, null=True)
    contents = models.TextField()

class FileUpload(models.Model):
    title = models.TextField(max_length=40, null=True)
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    content = models.TextField()

    def __str__(self):
        return self.title
# Create your models here.

main/views.py
from django.shortcuts import render , redirect
from .models import Post
from .form import FileUploadForm
from .models import  FileUpload

def index(request):
    return render(request, 'main/index.html')

# def blog(request):
#     postlist = Post.objects.all()
#     return render(request, 'main/blog.html', {'postlist':postlist})

def blog(request):
    postlist = FileUpload.objects.all()
    return render(request, 'main/blog.html', {'postlist':postlist})

# def posting(request, pk):
#     post = Post.objects.get(pk=pk)
#     return render(request, 'main/posting.html', {'post':post})

def posting(request, pk):
    post = FileUpload.objects.get(pk=pk)
    return render(request, 'main/posting.html', {'post':post})

def fileUpload(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        img = request.FILES["imgfile"]
        fileupload = FileUpload(
            title=title,
            content=content,
            imgfile=img,
        )
        fileupload.save()
        return redirect('main:blog')
    else:
        fileuploadForm = FileUploadForm
        context = {
            'fileuploadForm': fileuploadForm,
        }
        return render(request, 'main/fileupload.html', context)

def new_post(request):
    if request.method == 'POST':
        if request.POST['mainphoto']:
            new_article=Post.objects.create(
                postname=request.POST['postname'],
                contents=request.POST['contents'],
                mainphoto=request.POST['mainphoto'],
            )
        else:
            new_article=Post.objects.create(
                postname=request.POST['postname'],
                contents=request.POST['contents'],
                mainphoto=request.POST['mainphoto'],
            )
        return redirect('main:blog')
    return render(request, 'main/new_post.html')

# Create your views here.

templates/main/blog.html
{% extends 'base_new.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<html>
    <head>
        <title>board List</title>
    </head>
    <body>
        <h2>공지사항 </h2>
                    <div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
        </tr>
        </thead>
        <table>
        {% for list in postlist %}
            <ul>
                <li><a href="{{list.pk}}/">{{list.title}}</a></li>
            </ul>
        {% endfor %}
        </table>
                </body>
</html>
                <br>
                <br>
                <br>
                <br>
                <br>

<button><a href="{% url 'main:fileupload' %}">공지작성</a></button>
{% endblock %}

templates/main/fileupload.html
{% extends 'base_new.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
    <form method="POST" action="{% url 'main:fileupload' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form fileuploadForm %}
        <input type="submit" class="btn btn-primary col-12" value="제출">
    </form>
</div>
{% endblock%}

templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    장고 첫페이지!
</body>
</html>

templates/main/new_post.html
{% extends 'base_new.html' %}
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글쓰기 페이지</title>
</head>
<body>
    <h1>글쓰기 페이지</h1>
    <form method="post">
        {% csrf_token %}
        제목<br>
        <input type="text" name="postname"><br>
        내용<br>
        <textarea rows="10" cols="50" name="contents"></textarea><br>
        <input type="file" name="mainphoto"><br>
        <input type="submit" value="글쓰기">
    </form>
</body>
</html>
{% endblock %}

templates/main/posting.html
{% extends 'base_new.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<html>
    <head>
        <title>Posting!</title>
    </head>
    <body>
        <p>{{post.title}}</p>
        <br>

        <p>{{post.content}}</p>
        <br>

        <!-- 이미지 보여주기 -->
        {% if post.imgfile %}
            <img src = "../..{{ post.imgfile.url }}" alt="" height="300">
            <br>
        {% endif %}

        <br>
        <br>
        <br>
        <br>

        <a href="blog/">목록</a>
    </body>
</html>
{% endblock %}