config/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index_login, name = 'index_login' ),
    path('index', views.index, name= 'index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),

    #qna
    path('notice/', include('notice.urls')),
    #공지
    path('main/', include('main.urls')),

    #네이버 크롤링
    path('naver_crawling/', include('naver_crawling.urls')),

    #covid
    path('covid/', include('covid.urls')),
    # path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('users/password_reset_complete/', views.view_complete, name="password_reset_complete"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete2'),
    path('account/', include('allauth.urls')),  #소셜로그인 추가부분
    path('account/google/login/callback/index/',views.index),
    path('account/kakao/login/callback/index/',views.index),
    path('account/naver/login/callback/index/',views.index),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from main.views import index, blog, posting
from.views import *

from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('blog/', blog, name='blog'),
    path('blog/<int:pk>/', posting, name='posting'),
    path('fileupload/', fileUpload, name="fileupload"),
    path('blog/new_post/', new_post, name="new_post"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

naver_crawling/urls.py
from django.urls import path

from . import views


app_name = 'naver_crawling'

urlpatterns = [
    path('', views.naver_crawling, name='naver_crawling'),
    path('naver_title/', views.naver_title, name='naver_title'),
    path('naver_comment/', views.naver_comment, name='naver_comment'),
    #naver_crawling/ = ''
    # path('', views.NaverTitle, name='NaverTitle'),
    # path('', views.NVTitle, name='NVTitle'),
    # path('', views.NVComment, name='NVComment'),
]

users/urls.py
from django.urls import path
# 장고가 제공하는 로그인뷰와 로그인/로그아웃 기능 사용할 것임
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'users'

urlpatterns = [
    path('', views.index_login, name='index_login'),
    path('login/index/', views.index, name='index'),
    # path('user/create/', views.user_vreate, name='user_create'),
    # path('login/',views.login, name='login'),
    # path('logout/',views.logout, name='logout'),
    # path('user/info/', views.user_info, name='user_info'),
    # path('user/info/update', views.user_info_update, name='user_info_update'),
    # path('user/info/delete', views.user_delete, name='user_delete'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    # path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    # path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('send_email/', views.send_email, name='send_email'),

    #회원정보 업데이트
    path('update/', views.update, name='update'),
    #회원삭제
    path('delete/', views.delete, name='delete'),
    #비밀번호 변경
    path('password/', views.change_password, name='password'),

    #아이디 찾기
    path('forgot_id/', views.forgot_id, name='forgot_id'),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

naver_crawling/models.py
from django.db import models

# 많이 본 뉴스
class NaverTitle(models.Model):
    create_date = models.DateField()
    name = models.CharField(max_length=50)
    link = models.TextField()
    title = models.TextField()
    content = models.TextField()

    class Meta:
        db_table = u'NEWS_TITLE_FINAL'

    def __str__(self):
        return str(self.name)

# 댓글 많은 뉴스
class NaverComment(models.Model):
    create_date = models.DateField()
    name = models.CharField(max_length=50)
    link = models.TextField()
    title = models.TextField()
    content = models.TextField()

    class Meta:
        db_table = u'NEWS_COMMENT_FINAL'

    def __str__(self):
        return str(self.name)

naver_crawling/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import NaverTitle, NaverComment
import time


# Create your views here.
def naver_title(request):
    # result_comment_22Jul29.png
    filename = time.strftime("../../static/naver_crawling/main/title_pngfile/result_title_%y%b%d.png")
    form = {'filename': filename}
    content = {'form': form}
    return render(request, 'naver_crawling/naver_title.html',content)



def naver_comment(request):
    filename = time.strftime("../../static/naver_crawling/main/comment_pngfile/result_comment_%y%b%d.png")
    form = {'filename': filename}
    content = {'form': form}
    return render(request, 'naver_crawling/naver_comment.html', content)



def naver_crawling(request):
    navertitles = NaverTitle.objects.all()
    context = {'navertitles':navertitles}
    return render(request, 'naver_crawling/naver_crawling.html', context)


# create_date='날짜', name='언론사', title='제목'
# ['name']['link']['title']

templates/naver_crawling/naver_comment.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EasyWay</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
<!--    ====-->
    <link rel="stylesheet" href="{% static 'assets/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">
</head>

<body>
    <!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
<!--                    <li>-->
<!--                        <a href="index.html"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>-->
<!--                    </li>-->
                    <li class="menu-title"><a href="../">네이버 뉴스 크롤링</a></li><!-- /.menu-title -->
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">뉴스 크롤링 시각화</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="fa fa-book"></i><a href="{% url 'naver_crawling:naver_title' %}">많이 본 뉴스 시각화</a></li>
                            <li><i class="fa fa-book"></i><a href="{% url 'naver_crawling:naver_comment' %}">댓글 많은 뉴스 시각화</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>
    <!-- /#left-panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        <header id="header" class="header">
            <div class="top-left">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'users:index'%}"><img src="{% static 'images/logo.png' %}" alt="Logo"></a>
                    <a class="navbar-brand hidden" href="{% url 'users:index'%}"><img src="{% static 'images/logo2.png' %}" alt="Logo"></a>
                    <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
                </div>
            </div>
            <div class="top-right">
                <div class="header-menu">
<!--                    <div class="header-left">-->
<!--                        <button class="search-trigger"><i class="fa fa-search"></i></button>-->
<!--                        <div class="form-inline">-->
<!--                            <form class="search-form">-->
<!--                                <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">-->
<!--                                <button class="search-close" type="submit"><i class="fa fa-close"></i></button>-->
<!--                            </form>-->
<!--                        </div>-->

<!--                        <div class="dropdown for-notification">-->
<!--                            <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--                                <i class="fa fa-bell"></i>-->
<!--                                <span class="count bg-danger">3</span>-->
<!--                            </button>-->
<!--                            <div class="dropdown-menu" aria-labelledby="notification">-->
<!--                                <p class="red">You have 3 Notification</p>-->
<!--                                <a class="dropdown-item media" href="#">-->
<!--                                    <i class="fa fa-check"></i>-->
<!--                                    <p>Server #1 overloaded.</p>-->
<!--                                </a>-->
<!--                                <a class="dropdown-item media" href="#">-->
<!--                                    <i class="fa fa-info"></i>-->
<!--                                    <p>Server #2 overloaded.</p>-->
<!--                                </a>-->
<!--                                <a class="dropdown-item media" href="#">-->
<!--                                    <i class="fa fa-warning"></i>-->
<!--                                    <p>Server #3 overloaded.</p>-->
<!--                                </a>-->
<!--                            </div>-->
<!--                        </div>-->

<!--                        <div class="dropdown for-message">-->
<!--                            <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--                                <i class="fa fa-envelope"></i>-->
<!--                                <span class="count bg-primary">4</span>-->
<!--                            </button>-->
<!--                            <div class="dropdown-menu" aria-labelledby="message">-->
<!--                                <p class="red">You have 4 Mails</p>-->
<!--                                <a class="dropdown-item media" href="#">-->
<!--                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/1.jpg"></span>-->
<!--                                    <div class="message media-body">-->
<!--                                        <span class="name float-left">Jonathan Smith</span>-->
<!--                                        <span class="time float-right">Just now</span>-->
<!--                                        <p>Hello, this is an example msg</p>-->
<!--                                    </div>-->
<!--                                </a>-->
<!--                                <a class="dropdown-item media" href="#">-->
<!--                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/2.jpg"></span>-->
<!--                                    <div class="message media-body">-->
<!--                                        <span class="name float-left">Jack Sanders</span>-->
<!--                                        <span class="time float-right">5 minutes ago</span>-->
<!--                                        <p>Lorem ipsum dolor sit amet, consectetur</p>-->
<!--                                    </div>-->
<!--                                </a>-->
<!--                                <a class="dropdown-item media" href="#">-->
<!--                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/3.jpg"></span>-->
<!--                                    <div class="message media-body">-->
<!--                                        <span class="name float-left">Cheryl Wheeler</span>-->
<!--                                        <span class="time float-right">10 minutes ago</span>-->
<!--                                        <p>Hello, this is an example msg</p>-->
<!--                                    </div>-->
<!--                                </a>-->
<!--                                <a class="dropdown-item media" href="#">-->
<!--                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/4.jpg"></span>-->
<!--                                    <div class="message media-body">-->
<!--                                        <span class="name float-left">Rachel Santos</span>-->
<!--                                        <span class="time float-right">15 minutes ago</span>-->
<!--                                        <p>Lorem ipsum dolor sit amet, consectetur</p>-->
<!--                                    </div>-->
<!--                                </a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->

                   {% if user.is_authenticated %}
                    <div class="user-area dropdown float-right"> <!--  유저이미지 삭제해야함-->
                        <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            WellCome {{ user.username }}
                        </a>

                        <div class="user-menu dropdown-menu"> <!-- 사용자 개인메뉴 -->

                            {% if request.user == user %}
                            <a class="nav-link" href="{% url 'users:update' %}"><i class="fa fa- user"></i>회원정보 수정</a>

<!--                            <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>-->

<!--                            <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>-->

                            <a class="nav-link" href="{% url 'users:logout' %}"><i class="fa fa-power -off"></i>로그 아웃</a>
                            {% endif %}
                            {% else %}
                            <a class="nav-link" href="{% url 'users:login' %}"><i class="fa fa-power -on"></i>Login</a>

                        </div>
                    </div>
                    {% endif %}

                </div>
            </div>
        </header>
        <!-- Header-->


        <!-- Content -->
        <div class="content">
            <div class="animated fadeIn">
                <div class="row">

                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="mb-3">댓글 많은 뉴스 시각화 </h4>
<!--                                <canvas id="sales-chart"></canvas>-->
                                <img src="{{form.filename}}">
                            </div>
                        </div>
                    </div>
                </div>

            </div><!-- .animated -->
        </div>
        <!-- /.content -->


        <div class="clearfix"></div>

        <footer class="site-footer">
<!--            <div class="footer-inner bg-white">-->
<!--                <div class="row">-->
<!--                    <div class="col-sm-6">-->
<!--                        Copyright &copy; 2018 Ela Admin-->
<!--                    </div>-->
<!--                    <div class="col-sm-6 text-right">-->
<!--                        Designed by <a href="https://colorlib.com">Colorlib</a>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
        </footer>

    </div><!-- /#right-panel -->

    <!-- Right Panel -->

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
<!--    <script src="{% static 'assets/js/main.js' %}"></script>-->


<!--    <script src="{% static 'assets/js/lib/data-table/datatables.min.js' %}"></script>-->
<!--    <script src="{% static 'assets/js/lib/data-table/dataTables.bootstrap.min.js'%}"></script>-->
<!--    <script src="{% static 'assets/js/lib/data-table/dataTables.buttons.min.js'}"></script>-->
<!--    <script src="{% static 'assets/js/lib/data-table/buttons.bootstrap.min.js' %}"></script>-->
<!--    <script src="{% static 'assets/js/lib/data-table/jszip.min.js' %}"></script>-->
<!--    <script src="{% static 'assets/js/lib/data-table/vfs_fonts.js' %}"></script>-->
<!--    <script src="{% static 'assets/js/lib/data-table/buttons.html5.min.js' %}"></script>-->
<!--    <script src="{% static 'assets/js/lib/data-table/buttons.print.min.js' %}"></script>-->
<!--    <script src="{% static 'assets/js/lib/data-table/buttons.colVis.min.js' %}"></script>-->
<!--    <script src="{% static 'assets/js/init/datatables-init.js' %}"></script>-->


    <script type="text/javascript">
        $(document).ready(function() {
          $('#bootstrap-data-table-export').DataTable();
      } );
  </script>


</body>
</html>