config/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index_login, name = 'index_login' ),
    path('index', views.index, name= 'index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),

    #qna
    path('notice/', include('notice.urls')),
    #공지
    path('main/', include('main.urls')),

    #네이버 크롤링
    path('naver_crawling/', include('naver_crawling.urls')),

    #covid
    path('covid/', include('covid.urls')),
    # path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('users/password_reset_complete/', views.view_complete, name="password_reset_complete"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete2'),
    path('account/', include('allauth.urls')),  #소셜로그인 추가부분
    path('account/google/login/callback/index/',views.index),
    path('account/kakao/login/callback/index/',views.index),
    path('account/naver/login/callback/index/',views.index),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from main.views import index, blog, posting
from.views import *

from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('blog/', blog, name='blog'),
    path('blog/<int:pk>/', posting, name='posting'),
    path('fileupload/', fileUpload, name="fileupload"),
    path('blog/new_post/', new_post, name="new_post"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
# 장고가 제공하는 로그인뷰와 로그인/로그아웃 기능 사용할 것임
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'users'

urlpatterns = [
    path('', views.index_login, name='index_login'),
    path('login/index/', views.index, name='index'),
    # path('user/create/', views.user_vreate, name='user_create'),
    # path('login/',views.login, name='login'),
    # path('logout/',views.logout, name='logout'),
    # path('user/info/', views.user_info, name='user_info'),
    # path('user/info/update', views.user_info_update, name='user_info_update'),
    # path('user/info/delete', views.user_delete, name='user_delete'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    # path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    # path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('send_email/', views.send_email, name='send_email'),

    #회원정보 업데이트
    path('update/', views.update, name='update'),
    #회원삭제
    path('delete/', views.delete, name='delete'),
    #비밀번호 변경
    path('password/', views.change_password, name='password'),

    #아이디 찾기
    path('forgot_id/', views.forgot_id, name='forgot_id'),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

class Post(models.Model):
    postname = models.CharField(max_length=50)
    # 게시글 Post에 이미지 추가
    mainphoto = models.ImageField(upload_to="", blank=True, null=True)
    contents = models.TextField()

class FileUpload(models.Model):
    title = models.TextField(max_length=40, null=True)
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    content = models.TextField()

    def __str__(self):
        return self.title
# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .validators import validate_phone
# Create your models here.

# class User(models.Model):
#     id = models.CharField(max_length=32, primary_key=True, verbose_name='사용자 아이디')
#     pwd = models.CharField(max_length=64, verbose_name='사용자 비밀번호')
#     salt = models.CharField(max_length=32, verbose_name='암호화용 salt')
#     name = models.CharField(max_length=16, verbose_name='사용자 이름')
#     phone = models.CharField(max_length=13, unique=True, verbose_name='휴대폰 번호')
#     ssn = models.CharField(max_length=14, unique=True, verbose_name='주민번호')
#     email = models.EmailField(max_length=64, unique=True, verbose_name='이메일')
#     gender = models.CharField(max_length=1,default='M', verbose_name='성별')
#     admin = models.CharField(max_length=1, default='N', blank=True, verbose_name='관리자유무')
#     reg_date = models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         constraints = [
#             models.CheckConstraint(check=(models.Q(admin='Y')   # admin 에 대한 check 제약조건
#                                        | models.Q(admin='N')),name='admin check constraint'),
#             models.CheckConstraint(check=(models.Q(gender='F')  # gender 에 대한 check 제약조건
#                                           | models.Q(gender='M')), name='gender check constraint'),
#         ]

#https://velog.io/@nathan29849/Django-User-%EB%AA%A8%EB%8D%B8%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-Signup-User-%ED%99%95%EC%9E%A5
#상속하여 User생성
class User(AbstractUser):
    phone = models.CharField(max_length=11, unique=True, verbose_name='휴대폰 번호',validators=[validate_phone]) # 11로 바꾸기

    def __str__(self):
        return self.username

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms
from .validators import validate_phone
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
class UserForm(UserCreationForm):
    # 추가할 필드 속성
    first_name = forms.CharField(max_length=150, label='이름')
    email = forms.EmailField(label='이메일')
    phone = forms.CharField(max_length=11, validators=[validate_phone], label='휴대전화')
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'first_name', 'email',  'phone')
        labels = {
            'username': '아이디',
            'password1': '비밀번호',
            'password2': '비밀번호 재확인',
            'first_name': '이름',
            'email': '이메일',
            'phone': '휴대전화',
        }


class CustomUserChangeForm(UserChangeForm):
    phone = forms.CharField(max_length=11, validators=[validate_phone], label='휴대전화')
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'email', 'phone']
        labels = {
            'username': '아이디',
            'first_name': '이름',
            'email': '이메일',
            'phone': '휴대전화',
        }

class Get_UserIDForm(forms.ModelForm):
    pass


class CustomUserChangeForm2(UserChangeForm):
    phone = forms.CharField(max_length=11, validators=[validate_phone], label='휴대전화')
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'email', 'phone']
        labels = {
            'username': '아이디',
            'first_name': '이름',
            'email': '이메일',
            'phone': '휴대전화',
        }

users/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect


from .forms import UserForm
from django.core.validators import validate_email
# Create your views here.
from .validators import validate_name

# 페이징 처리를 위한 클래스 임포트함


# HttpRequest : 서버로 오는 클라이언트 요청 객체
#HttpResponse : 서버에서 요청한 클라이언트로 답을 보내는 객체

# Create your views here.
# 브라우저 url 에서 ..../pyboard/ 서비스 요청시
# 등록된 url 매핑에 의해서 views.index 함수가 응답처리됨

def index(request):
    return render(request, 'index.html')
def index_login(request):
    return render(request, 'users/login.html')
# from .forms import BoardForm, UserCreateForm # UserCreateForm를 import한다.
# from django.contrib.auth.models import User # User 모델을 import한다.
from .models import User

def signup(request):
    if request.method == "POST": # 회원가입 폼의 값이 전송오면
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'users/signup.html', {'form': form})


from django.core.mail.message import EmailMessage

def send_email(request):
    subject = "message"
    to = ["tjgyqo2@gmail.com"]
    from_email = "tjgyqo2@gmail.com"
    message = "메지시 테스트"
    EmailMessage(subject=subject, body=message, to=to, from_email=from_email).send()


from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)
from django.urls import reverse_lazy

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
class UserPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset.html'  # 템플릿을 변경하려면 이와같은 형식으로 입력
    success_url = reverse_lazy('password_reset_done')
    form_class = PasswordResetForm

    def form_valid(self, form):
        if User.objects.filter(username=self.request.POST.get("username")).exists() and \
                User.objects.get(username=self.request.POST.get("username")).email == self.request.POST.get("email"):
            return super().form_valid(form)
        else:
            return render(self.request, 'users/password_reset_done_fail.html')

class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'  # 템플릿을 변경하려면 이와같은 형식으로 입력

class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('password_reset_complete')
    form_class = SetPasswordForm
    def form_valid(self, form):
        return super().form_valid(form)

def view_complete(request):
    return render(request, 'users/password_reset_complete.html')

# 정보변경
from django.contrib.auth.forms import UserChangeForm
from .forms import CustomUserChangeForm2
from .validators import validate_phone

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm2(request.POST, instance=request.user)
        if form.is_valid() and validate_phone(form.cleaned_data.get('phone')):
            print('valid')
            form.save()
            return redirect('users:index')
    else:
        form = CustomUserChangeForm2(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'users/update.html', context)

@login_required
def delete(request):
    if request.method == 'POST':
        request.user.delete()
        return redirect('users:login')
    return render(request, 'users/delete.html')

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            # 로그아웃 되지 않도록 새로운 password hash로 session을 업데이트함
            return redirect('users:index')
    else:
        form = PasswordChangeForm(request.user)

    context = {'form': form,}
    return render(request, 'users/change_password.html', context)
    # 위와 같은 상황에서 비밀번호를 바꾸면 로그아웃이 되어버림. 사용자 정보가 바뀌었기 때문에

from .utils import send_sms
from django.contrib import messages

def forgot_id(request):
    context = {}
    if request.method == 'POST':
        phone = request.POST.get('phone').replace('-','')
        try:
            user = User.objects.get(phone=phone)
            if user is not None:
                send_sms(user)
                return render(request, 'users/forgot_id_complete.html', context)
        except:
            messages.info(request, "해당하는 번호가 존재하지 않습니다.")

    return render(request, 'users/forgot_id.html', context)

#문자보내기

templates/users/change_password.html
{% extends "base_new.html" %}
{% load bootstrap4 %}
{% block content %}

<h1>User password change</h1>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary btn-flat m-b-15" type="submit" value="submit"/>
</form>

{% endblock %}

templates/users/forgot_id.html
{% extends "base_new.html" %}

{% block content %}



<body class="bg-dark">

    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">

                <div class="login-form">
                    <form class ="post-form" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="phone">휴대폰번호</label>
                                <input type="phone" class="form-control" placeholder="010-1234-5678" name="phone" id="phone">
                        </div>
                        <p class="info-msg mt10">
                            가입하실때 작성하신 휴대폰 번호를 입력해주세요.<br>
                            입력하신 휴대폰의 카톡 또는 문자로 가입하신 ID를 보내드립니다.
                        </p>
                        <button type="submit" class="btn btn-primary btn-flat m-b-15">아이디 찾기</button>
                        {% for message in messages %}
                            {{message}}
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
    </div>



</body>
{% endblock %}

templates/users/forgot_id_complete.html
{% extends "base_new.html" %}


{% block content %}



<body class="bg-dark">

    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="{% url 'users:login' %}">
                        <img class="align-content" src="images/logo.png" alt="">
                    </a>
                </div>
                <div class="container my-3">
                    <h4 style="color:white;" class="border-bottom pb-2 my-3">메세지 전송 완료!</h4>
                    <p style="color:white;" >휴대폰 메세지를 확인하세요.</p>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">로그인</a>
                </div>
            </div>
        </div>
    </div>

</body>

{% endblock %}

templates/users/info.html
<div class="container">
    <h1> {{ people.username }}</h1>
    {% if user == people %}
    <div>
    <a href="{% url 'users:update' %}">계정정보수정</a>
    </div>
    {% endif %}
    <div class="row">
        {% for post in people.post_set.all %}
        <div class="col-4">
            <img src= "{{ post.image_set.first.file.url }}" class="img-fluid"/>
        </div>
        {% endfor %}
    </div>
</div>

templates/users/login.html
{% load socialaccount %}
{% load static %}
{% providers_media_js %}
{% block content %}
{% load i18n %}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EasyWay</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<!--    <link rel="stylesheet" href="{% static 'assets/css/bootstrap-social.css' %}">-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>



    <link rel="stylesheet" href="https://gnustudy.com/skin/social/style.css?ver=190112">

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
</head>
<body class="bg-dark">

    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="#">
                        <img class="align-content" src="{% static 'images/logo.png' %}" alt="">
                    </a>
                </div>

                <div class="login-form">
                    <form method="post" action="{% url 'users:login' %}">
                        {% csrf_token %}
                        {% include "form_errors.html" %}
                        <div class="form-group">
                            <label for="username">Id</label>
                            <input type="text" class="form-control" placeholder="Id" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" placeholder="Password" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
                        </div>
                        <div class="checkbox">
<!--                            <label>-->
<!--                                <input type="checkbox"> Remember Me-->
<!--                            </label>-->
                            <label class="pull-right">
                                Forgotten<a href="{% url 'users:forgot_id'%}"> ID?</a> | <a href="../../password_reset/">Password?</a>
                            </label>

                        </div>
                        <button type="submit" class="btn btn-success btn-flat m-b-30 m-t-30">Sign in</button>

<!--                        <div class="social-login-content">-->
<!--                            <div class="social-button">-->
<!--                                <button type="button" class="btn social twitter btn-flat btn-addon mt-2" style="background-color: #DD4B39;" onclick="window.location.href='{% provider_login_url 'google' %}'" ><i class="google"></i>Google로 로그인</button>-->
<!--                                <button type="button" class="btn social kakao btn-flat btn-addon mt-2" onclick="window.location.href='{% provider_login_url 'kakao' %}'"><i class="ti-twitter"></i>Kakao로 로그인</button>-->
<!--                                <button type="button" class="btn social twitter btn-flat btn-addon mt-2" onclick="window.location.href='{% provider_login_url 'naver' %}'"><i class="ti-twitter"></i>Naver로 로그인</button>-->
<!--                            </div>-->
<!--                        </div>-->

                        <style>
                            #sns_login {
                                width: 100%;

                                margin: 0;
                                padding: 0;
                            }
                        </style>
<!--                        <div id="sns_login" class="login-sns sns-wrap-32 sns-wrap-over">-->
                        <div id="sns_login" class="login-sns sns-wrap-32 sns-wrap-over">
                        <h3>소셜계정으로 로그인</h3>
                        <div class="sns-wrap">
                            <a href="{% provider_login_url 'google' %}"  class="sns-icon social_link sns-google" title="구글">
                                <span class="ico"></span>
                                <span class="txt">구글<i> 로그인</i></span>
                            </a>
                        </div>
                        <div class="sns-wrap">
                            <a href="{% provider_login_url 'kakao' %}"  class="sns-icon social_link sns-kakao" title="카카오">
                                <span class="ico"></span>
                                <span class="txt">카카오<i> 로그인</i></span>
                            </a>
                        </div>
                        <div class="sns-wrap">
                            <a href="{% provider_login_url 'naver' %}"  class="sns-icon social_link sns-naver" title="네이버">
                                <span class="ico"></span>
                                <span class="txt">네이버<i> 로그인</i></span>
                            </a>
                        </div>
                        </div>
<!--                        </div>-->
                    </form>
                        <div class="register-link m-t-15 text-center">
                            <p>Don't have account ? <a href="{% url 'users:signup' %}"> Sign Up Here</a></p>
                        </div>

                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>
{% endblock %}

templates/users/login_old.html
{% extends "base.html" %}
{% load socialaccount %}
{% load static %}
{% providers_media_js %}
{% block content %}
{% load i18n %}
<div class="container my-3">
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button><br>
    </form>
        <a href="../../password_reset/"><button type="button" class="btn btn-dark">비밀번호찾기</button></a><a href="../../find_id/"><button type="button" class="btn btn-dark">아이디찾기</button></a>
    <ul>
	    <li><a href="{% provider_login_url 'google' %}"><img src="{% static 'images/google.png' %}" width="200"></a></li>
        <li><a href="{% provider_login_url 'kakao' %}"><img src="{% static 'images/kakao.png' %}" width="200"></a><br></li>
        <li><a href="{% provider_login_url 'naver' %}"><img src="{% static 'images/naver.png' %}" width="200"></a><br></li>
    </ul>

</div>
{% endblock %}

templates/users/password_reset_complete.html
{% extends "base_new.html" %}


{% block content %}



<body class="bg-dark">

    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="index.html">
                        <img class="align-content" src="images/logo.png" alt="">
                    </a>
                </div>
                <div class="container my-3">
                    <h4 style="color:white;" class="border-bottom pb-2 my-3">비밀번호 초기화 완료</h4>
                    <p style="color:white;" >비밀번호가 재설정되었습니다. 이제 로그인하세요!</p>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">로그인</a>
                </div>
            </div>
        </div>
    </div>

</body>

{% endblock %}

templates/users/update.html
{% extends "base_new.html" %}
{% load bootstrap4 %}
{% block content %}

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<style>

</style>


</head>
<body>
<h1>User Edit</h1>



    <form action="" method="POST">
        {% csrf_token %}
        {% include "../form_errors.html" %}
        <input type="hidden" value="{{ form.id.value|default_if_none:'' }}">
        <div class="form-group"><label for="id_username">사용자 이름</label><input type="text" name="username" value="{{ form.username.value|default_if_none:'' }}" maxlength="150" class="form-control" placeholder="사용자 이름" title="150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다." required="" id="id_username">
        <small class="form-text text-muted">150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다.</small>
        </div>
        <div class="form-group"><label for="id_first_name">이름</label><input type="text" name="first_name" value="{{ form.first_name.value|default_if_none:'' }}" maxlength="150" class="form-control" placeholder="이름" title="" id="id_first_name"></div>
        <div class="form-group"><label for="id_email">이메일 주소</label><input type="email" name="email" value="{{ form.email.value|default_if_none:'' }}" maxlength="254" class="form-control" placeholder="이메일 주소" title="" id="id_email"></div>
        <div class="form-group"><label for="id_phone">휴대폰 번호</label><input type="text" name="phone" value="{{ form.phone.value|default_if_none:'' }}" maxlength="11" class="form-control" placeholder="휴대폰 번호" title="" required="" id="id_phone"></div>
        <label class="pull-right">
                                <a style="color: red;" href="{% url 'users:password' %}">비밀번호 변경</a>
                            </label>
        <button class="btn btn-primary">수정</button>

    </form>
    <br><br>
    <div style="text-align: right;"><a href="{% url 'users:delete' %}" class="btn btn-danger">회원탈퇴</a></div>
</body>


{% endblock %}